# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
    push:
        branches: [master]

jobs:

    # Code Stage (with Shift left)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    # Secret Scanning
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    # Dependency Checks
    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml

    # Docker Checks
    docker-checks:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit 

    # SonarQube
    sonar-qube:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit

    # Code Tests
    code-tests:
        uses: ./.github/workflows/code-test.yml

    # push-to-docker-hub:
    docker-push:
        uses: ./.github/workflows/docker-push.yml
        needs: [code-quality,code-tests,sonar-qube,docker-checks,dependency-checks,secret-scanning]
        secrets: inherit